[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install --build-from-source"

[deploy]
startCommand = "cd backend && node src/db/seed.js; node src/app.js"
restartPolicyType = "always"

[[services]]
name = "forge"
